wtyicy:
  # 文件存储地址 默认 wtyicy
  filePath: wtyicy
  # 默认上传云端  默认 qiniuyun
  defaultType: baiduyun
  # ===================================================================
  # 阿里云对象存储
  # ===================================================================
  aliyun:
    # 上传地址
    endpoint: http://oss-cn-beijing.aliyuncs.com/
    # ID
    accessKeyId: LTAIJ9Xt8S8sqCdp
    # 密钥
    accessKeySecret: 11KZPPlpjm6Uq7hElmfnAWLxYNsqEg
    # 存储桶
    bucketName: wtyicy
    # 访问地址
    url: https://wtyicy.oss-cn-beijing.aliyuncs.com/
  # ===================================================================
  # 七牛云对象存储
  # ===================================================================
  qiniuyun:
    # 存储和访问地址
    endpoint: http://java68.cn/
    # Id
    accessKeyId: Wm4Px8htNf_vNLKy-WHxvp7s-cofYW75qRrX93Zo
    # 密钥
    accessKeySecret: mvfBJfh9ieDC9j6IUS13TD-Eq2488dOAhRFvr70z
    # 存储桶
    bucketName: wtyicy
  # ===================================================================
  # 分布式文件系统FDFS配置
  # ===================================================================
  fdfs:
    # 访问地址
    url: http://10.211.55.7:8888/
    # 上传地址
    trackerList:
      - 10.211.55.7:22122
  # ===================================================================
  # 腾讯云对象存储
  # ===================================================================
  qcloudyun:
    # ID
    accessKeyId: AKID40nyhBFPL3Vw8ATT1UjiQs69vER3HbsF
    # 密钥
    accessKeySecret: G4fLkxukN8i1H4b2S1288tpXFi09FB5k
    # 上传区域地点
    bucket: ap-chengdu
    # 存储桶
    bucketName: wtyicy-1255846851
    # 访问地址
    url: https://wtyicy-1255846851.cos.ap-chengdu.myqcloud.com/
  # ===================================================================
  # 百度云对象存储
  # ===================================================================
  baiduyun:
    # Id
    accessKeyId: 4d33d49b2c8944efa238e6e59d1da257
    # 密钥
    accessKeySecret: e2f4057c26d84287967053b1f2c6b3ac
    # 存储桶
    bucketName: cyiwty
    # 访问地址
    url: https://cyiwty.cdn.bcebos.com/
    # 上传地址
    endpoint: https://cyiwty.bj.bcebos.com/
  # ===================================================================
  # 华为云对象存储
  # ===================================================================
  huaweiyun:
    # Id
    accessKeyId: DXD3BOINK9SR4JBZ3HIS
    # 密钥
    accessKeySecret: i7BYwsWj9N1yrMnlQPag7auaqeh36lF66LpqI433
    # 存储桶
    bucketName: wtyicy
    # 访问地址
    url: https://wtyicy.obs.cn-north-4.myhuaweicloud.com/
    # 上传地址
    endpoint: https://obs.cn-north-4.myhuaweicloud.com/
  # ===================================================================
  # 京东云对象存储
  # ===================================================================
  jingdongyun:
    # Id
    accessKeyId: 843788B23488E7CCC620882AE80FD1D3
    # 密钥
    accessKeySecret: 8A3A25925AA902442C9CEBFBAEEB498C
    # 存储桶
    bucketName: wtyicy
    # 上传区域地点
    bucket: cn-north-1
    # 访问地址
    url: https://wtyicy.s3.cn-north-1.jdcloud-oss.com/
    # 上传地址
    endpoint: https://s3.cn-north-1.jdcloud-oss.com/
